using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodetoryMenuGeorgian.Models.Italy
{
    public class Categories
    {
        public List<Categorie> categories { get; set; }
        public Categories()
        {
            categories = new List<Categorie>();
            List<Product> pizzas = new List<Product>();

            pizzas.Add(new Product { Name = "Pizza Pepperoni whole", NameArm = "Պիցցա Պեպերոնի ամբողջական", NameRus = "Пицца Пепперони целая", Price = "2700/550", PicPath = "/Resources/Italy/Պիցցա պեպերոնի ամբողջական.jpg", Description = "cheese, mozzarella, parmesan, Choriso sausage", DescriptionArm = "պանիր, մոցառելլա, պարմեզան, երշիկ Choriso", DescriptionRus = "сыр, моцарелла, пармезан, колбаса Choriso" });
            pizzas.Add(new Product { Name = "Pizza Pepperoni 1 piece", NameArm = "Պիցցա Պեպերոնի 1 կտոր", NameRus = "Пицца Пепперони 1 кусок", Price = "2700/550", PicPath = "/Resources/Italy/Պիցցա պեպերոնի 1 կտոր.jpg", Description = "cheese, mozzarella, parmesan, Choriso sausage", DescriptionArm = "պանիր, մոցառելլա, պարմեզան, երշիկ Choriso", DescriptionRus = "сыр, моцарелла, пармезан, колбаса Choriso" });
            pizzas.Add(new Product { Name = "Pizza Margarita whole", NameArm = "Պիցցա Մարգարիտա ամբողջական", NameRus = "Пицца Маргарита целая", Price = "1920/390", PicPath = "/Resources/Italy/Պիցցա Մարգարիտա ամբողջական.jpg", Description = "tomatoes, mozzarella, parmesan, basil", DescriptionArm = "լոլիկ, մոցառելլա,  պարմեզան, բազիլիկ", DescriptionRus = "помидоры, моцарелла, пармезан, базилик" });
            pizzas.Add(new Product { Name = "Pizza Margarita 1 piece", NameArm = "Պիցցա Մարգարիտա 1 կտոր", NameRus = "Пицца Маргарита 1 кусок", Price = "1920/390", PicPath = "/Resources/Italy/Պիցցա Մարգարիտա 1 կտոր.jpg", Description = "tomatoes, mozzarella, parmesan, basil", DescriptionArm = "լոլիկ, մոցառելլա,  պարմեզան, բազիլիկ", DescriptionRus = "помидоры, моцарелла, пармезан, базилик" });
            pizzas.Add(new Product { Name = "Pizza Caesar whole", NameArm = "Պիցցա Կեսար ամբողջական", NameRus = "Пицца Цезарь целая", Price = "2340/550", PicPath = "/Resources/Italy/Պիցցա կեսար ամբողջական.jpg", Description = "Caesar sauce, lettuce, chicken breast", DescriptionArm = "կեսարի սոուս, հազար, հավի կրծքամիս", DescriptionRus = "Соус Цезарь, листья салата, куриная грудка" });
            pizzas.Add(new Product { Name = "Pizza Caesar 1 piece", NameArm = "Պիցցա Կեսար 1 կտոր", NameRus = "Пицца Цезарь 1 кусок", Price = "2340/550", PicPath = "/Resources/Italy/Պիցցա կեսար 1 կտոր.jpg", Description = "Caesar sauce, lettuce, chicken breast", DescriptionArm = "կեսարի սոուս, հազար, հավի կրծքամիս", DescriptionRus = "Соус Цезарь, листья салата, куриная грудка" });
            pizzas.Add(new Product { Name = "Pizza Calzone big", NameArm = "Պիցցա Կալզոնե մեծ", NameRus = "Пицца Кальцоне большая", Price = "990/550", PicPath = "/Resources/Italy/Կալզոնե մեծ.jpg", Description = "fillet, mushrooms, champignons, mozzarella", DescriptionArm = "ֆիլե, սունկ, շամպինյոն,  մոցառելլա", DescriptionRus = "филе, грибы, шампиньоны, моцарелла" });
            pizzas.Add(new Product { Name = "Pizza Calzone small", NameArm = "Պիցցա Կալզոնե փոքր", NameRus = "Пицца Кальцоне маленькая", Price = "990/550", PicPath = "/Resources/Italy/Կալզոնե փոքր.jpg", Description = "fillet, mushrooms, champignons, mozzarella", DescriptionArm = "ֆիլե, սունկ, շամպինյոն,  մոցառելլա", DescriptionRus = "филе, грибы, шампиньоны, моцарелла" });
            pizzas.Add(new Product { Name = "Pizza with seafood whole", NameArm = "Պիցցա Ծովամթերքներ ամբողջական", NameRus = "Пицца с морепродуктами целая", Price = "3540/590", PicPath = "/Resources/Italy/Պիցցա Ծովամթերքներ ամբողջական.jpg", Description = "arugula, lettuce, cherry tomatoes, salmon", DescriptionArm = "ռուկկոլա, լետտուս, չերրի լոլիկ, սաղմոն", DescriptionRus = "руккола, листья салата, помидоры черри, лосось" });
            pizzas.Add(new Product { Name = "Pizza with seafood 1 piece", NameArm = "Պիցցա Ծովամթերքներ 1 կտոր", NameRus = "Пицца с морепродуктами 1 кусок", Price = "3540/590", PicPath = "/Resources/Italy/Պիցցա Ծովամթերքներ 1 կտոր.jpg", Description = "arugula, lettuce, cherry tomatoes, salmon", DescriptionArm = "ռուկկոլա, լետտուս, չերրի լոլիկ, սաղմոն", DescriptionRus = "руккола, листья салата, помидоры черри, лосось" });
            pizzas.Add(new Product { Name = "Pizza with bacon whole", NameArm = "Պիցցա Բեկոնով ամբողջական", NameRus = "Пицца с беконом целая", Price = "2340/450", PicPath = "/Resources/Italy/Պիցցա բեկոնով ամբողջական.jpg", Description = "bell pepper, cherry tomatoes, bacon", DescriptionArm = "բուլղարական պղպեղ,  չերրի լոլիկ, բեկոն", DescriptionRus = "болгарский перец, помидоры черри, бекон" });
            pizzas.Add(new Product { Name = "Pizza with bacon 1 piece", NameArm = "Պիցցա Բեկոնով 1 կտոր", NameRus = "Пицца с беконом 1 кусок", Price = "2340/450", PicPath = "/Resources/Italy/Պիցցա բեկոնով 1 կտոր.jpg", Description = "bell pepper, cherry tomatoes, bacon", DescriptionArm = "բուլղարական պղպեղ,  չերրի լոլիկ, բեկոն", DescriptionRus = "болгарский перец, помидоры черри, бекон" });
            pizzas.Add(new Product { Name = "Pizza with salami whole", NameArm = "Պիցցա Սալյամի ամբողջական", NameRus = "Пицца с салями целая", Price = "2700/450", PicPath = "/Resources/Italy/Պիցցա սալյամի ամբողջական.jpg", Description = "salami, cherry tomatoes, oregano, olives", DescriptionArm = "սալյամի,  չերրի լոլիկ, օրեգանո, սեւ ձիթապտուղ", DescriptionRus = "салями, помидоры черри, орегано, оливки" });
            pizzas.Add(new Product { Name = "Pizza with salami 1 piece", NameArm = "Պիցցա Սալյամի 1 կտոր", NameRus = "Пицца с салями 1 кусок", Price = "2700/450", PicPath = "/Resources/Italy/Պիցցա սալյամի 1 կտոր.jpg", Description = "salami, cherry tomatoes, oregano, olives", DescriptionArm = "սալյամի,  չերրի լոլիկ, օրեգանո, սեւ ձիթապտուղ", DescriptionRus = "салями, помидоры черри, орегано, оливки" });
            pizzas.Add(new Product { Name = "Pizza Roman whole", NameArm = "Պիցցա Հռոմեական ամբողջական", NameRus = "Пицца Римская целая", Price = "2700/550", PicPath = "/Resources/Italy/Պիցցա հռոմեական ամբողջական.jpg", Description = "arugula, bell pepper, pumpkin", DescriptionArm = "ռուկկոլա,  բուլղարական պղպեղ, դդմիկ", DescriptionRus = "руккола, болгарский перец, тыква" });
            pizzas.Add(new Product { Name = "Pizza Roman 1 piece", NameArm = "Պիցցա Հռոմեական 1 կտոր", NameRus = "Пицца Римская 1 кусок", Price = "2700/550", PicPath = "/Resources/Italy/Պիցցա Հռոմեական 1 կտոր.jpg", Description = "arugula, bell pepper, pumpkin", DescriptionArm = "ռուկկոլա,  բուլղարական պղպեղ, դդմիկ", DescriptionRus = "руккола, болгарский перец, тыква" });
            pizzas.Add(new Product { Name = "Pizza four cheeses whole", NameArm = "Պիցցա 4 պանիր ամբողջական", NameRus = "Пицца четыре сыра целая", Price = "2340/550", PicPath = "/Resources/Italy/Պիցցա 4 պանիր ամբողջական.jpg", Description = "cheddar cheese, mozzarella, parmesan, Dorblu", DescriptionArm = "պանիր չեդդեր, մոցառելլա, պարմեզան, դորբլյու", DescriptionRus = "сыр чеддер, моцарелла, пармезан, Дорблю" });
            pizzas.Add(new Product { Name = "Pizza four cheeses 1 piece", NameArm = "Պիցցա 4 պանիր 1 կտոր", NameRus = "Пицца четыре сыра 1 кусок", Price = "2340/550", PicPath = "/Resources/Italy/Պիցցա 4 պանիր 1 կտոր.jpg", Description = "cheddar cheese, mozzarella, parmesan, Dorblu", DescriptionArm = "պանիր չեդդեր, մոցառելլա, պարմեզան, դորբլյու", DescriptionRus = "сыр чеддер, моцарелла, пармезан, Дорблю" });
            pizzas.Add(new Product { Name = "Pizza Caprese whole", NameArm = "Պիցցա Կապրեզե ամբողջական", NameRus = "Пицца Капрезе целая", Price = "3300/550", PicPath = "/Resources/Italy/Պիցցա կապրեզե ամբողջական.jpg", Description = "mozzarella, milk pesto sauce, basil", DescriptionArm = "մոցառելլա, կաթնային պեստո սոուս, բազիլիկ", DescriptionRus = "моцарелла, молочный соус песто, базилик" });
            pizzas.Add(new Product { Name = "Pizza Caprese 1 piece", NameArm = "Պիցցա Կապրեզե 1 կտոր", NameRus = "Пицца Капрезе 1 кусок", Price = "3300/550", PicPath = "/Resources/Italy/Պիցցա կապրեզե 1 կտոր.jpg", Description = "mozzarella, milk pesto sauce, basil", DescriptionArm = "մոցառելլա, կաթնային պեստո սոուս, բազիլիկ", DescriptionRus = "моцарелла, молочный соус песто, базилик" });
            pizzas.Add(new Product { Name = "Pizza Verde whole", NameArm = "Պիցցա Վեռդե ամբողջական", NameRus = "Пицца Верде целая", Price = "2100/490", PicPath = "/Resources/Italy/Պիցցա Վեռդե ամբողջական.jpg", Description = "vegetable cream, arugula, mushrooms, tomatoes", DescriptionArm = "բանջարեղենային սերուցք, ռուկկոլա, սունկ, լոլիկ", DescriptionRus = "растительные сливки, руккола, грибы, помидоры" });
            pizzas.Add(new Product { Name = "Pizza Verde 1 piece", NameArm = "Պիցցա Վեռդե 1 կտոր", NameRus = "Пицца Верде 1 кусок", Price = "2100/490", PicPath = "/Resources/Italy/Պիցցա Վեռդե 1 կտոր.jpg", Description = "vegetable cream, arugula, mushrooms, tomatoes", DescriptionArm = "բանջարեղենային սերուցք, ռուկկոլա, սունկ, լոլիկ", DescriptionRus = "растительные сливки, руккола, грибы, помидоры" });
            pizzas.Add(new Product { Name = "Pizza roman with prosciutto whole", NameArm = "Հռոմեական պիցցա պրոշուտո ամբողջական", NameRus = "Пицца римская с прошутто целая", Price = "750/4500", PicPath = "/Resources/Italy/roman pizza proshuto whole.jpg", Description = "prosciutto, arugula, cherry tomatoes, cream cheese, mozzarella, gran spicco cheese", DescriptionArm = "պրոշուտո, ռուկոլլա, չերրի լոլիկ, կրեմ-պանիր, մոցառելլա, պանիր գրան սպիկկո", DescriptionRus = "прошутто, руккола, помидоры черри, крем чиз, моцарелла, сыр гран спико" });
            pizzas.Add(new Product { Name = "Pizza roman with prosciutto 1 piece", NameArm = "Հռոմեական պիցցա պրոշուտո 1 կտոր", NameRus = "Пицца римская с прошутто 1 кусок", Price = "750/4500", PicPath = "/Resources/Italy/roman pizza proshuto 1 piece.jpg", Description = "prosciutto, arugula, cherry tomatoes, cream cheese, mozzarella, gran spicco cheese", DescriptionArm = "պրոշուտո, ռուկոլլա, չերրի լոլիկ, կրեմ-պանիր, մոցառելլա, պանիր գրան սպիկկո", DescriptionRus = "прошутто, руккола, помидоры черри, крем чиз, моцарелла, сыр гран спико" });
            pizzas.Add(new Product { Name = "Pizza roman Pepperoni whole", NameArm = "Հռոմեական պիցցա պեպերոնի ամբողջական", NameRus = "Пицца римская Пепперони целая", Price = "690/4140", PicPath = "/Resources/Italy/roman pizza pepperoni whole.jpg", Description = "mozzarella, arugula, cherry tomatoes, pepperoni, gran spicco cheese", DescriptionArm = "մոցառելլա, ռուկոլա, չերրի լոլիկ, պեպերոնի, պանիր գրան սպիկկո", DescriptionRus = "моцарелла, руккола, помидоры черри, пепперони, сыр гран спико" });
            pizzas.Add(new Product { Name = "Pizza roman Pepperoni 1 piece", NameArm = "Հռոմեական պիցցա պեպերոնի 1 կտոր", NameRus = "Пицца римская Пепперони 1 кусок", Price = "690/4140", PicPath = "/Resources/Italy/Roman pizza pepperoni 1 piece.jpg", Description = "mozzarella, arugula, cherry tomatoes, pepperoni, gran spicco cheese", DescriptionArm = "մոցառելլա, ռուկոլա, չերրի լոլիկ, պեպերոնի, պանիր գրան սպիկկո", DescriptionRus = "моцарелла, руккола, помидоры черри, пепперони, сыр гран спико" });
            pizzas.Add(new Product { Name = "Pizza roman Caprese whole", NameArm = "Հռոմեական պիցցա կապրեզե ամբողջական", NameRus = "Пицца римская Капрезе целая", Price = "650/3900", PicPath = "/Resources/Italy/roman pizza caprese whole.jpg", Description = "mozzarella, gran spicco cheese, basil, cherry tomatoes", DescriptionArm = "մոցառելլա, գրան սպիկկո պանիր, բազիլիկ, չերրի լոլիկ", DescriptionRus = "моцарелла, сыр гран спико, базилик, помидоры черри" });
            pizzas.Add(new Product { Name = "Pizza roman Caprese 1 piece", NameArm = "Հռոմեական պիցցա կապրեզե 1 կտոր", NameRus = "Пицца римская Капрезе 1 кусок", Price = "650/3900", PicPath = "/Resources/Italy/Roman pizza caprese 1 piece.jpg", Description = "mozzarella, gran spicco cheese, basil, cherry tomatoes", DescriptionArm = "մոցառելլա, գրան սպիկկո պանիր, բազիլիկ, չերրի լոլիկ", DescriptionRus = "моцарелла, сыр гран спико, базилик, помидоры черри" });
            pizzas.Add(new Product { Name = "Pizza Italiano whole", NameArm = "Պիցցա Իտալիանո ամբողջական", NameRus = "Пицца Итальяно целая", Price = "3300/550", PicPath = "/Resources/Italy/Պիցցա իտալյանո ամբողջական.jpg", Description = "beef fillet, arugula, cherry tomatoes, cheese gran spicco, mozzarella", DescriptionArm = "տավարի ֆիլե, ռուկոլա, չերրի լոլիկ, պանիր գրան սպիկկո, մոցառելլա", DescriptionRus = "филе говядины, руккола, помидоры черри, сыр гран спико, сыр моцарелла" });
            pizzas.Add(new Product { Name = "Pizza Italiano 1 piece", NameArm = "Պիցցա Իտալիանո 1 կտոր", NameRus = "Пицца Итальяно 1 кусок", Price = "3300/550", PicPath = "/Resources/Italy/Պիցցա իտալիանո մեկ կտոր.jpg", Description = "beef fillet, arugula, cherry tomatoes, cheese gran spicco, mozzarella", DescriptionArm = "տավարի ֆիլե, ռուկոլա, չերրի լոլիկ, պանիր գրան սպիկկո, մոցառելլա", DescriptionRus = "филе говядины, руккола, помидоры черри, сыр гран спико, сыр моцарелла" });
            pizzas.Add(new Product { Name = "Respella", NameArm = "Ռեսպելլա", NameRus = "Респелла", Price = "2700", PicPath = "/Resources/Italy/Respella.jpg", Description = "chicken breast, arugula, cherry tomatoes, mozzarella, cream cheese", DescriptionArm = "հավի կրծքամիս, ռուկոլա, չերրի լոլիկ, մոցառելլա, սերուցքային պանիր", DescriptionRus = "куриная грудка, руккола, помидоры черри, моцарелла, сливочный сыр" });
            pizzas.Add(new Product { Name = "Estate in Italiano whole", NameArm = "Էստատե ին իտալյանո ամբողջական", NameRus = "Эстате ин Италиано целая", Price = "590/3540", PicPath = "/Resources/Italy/estante in italiano.jpg", Description = "black and green olives, cherry tomatoes, bell peppers, mozzarella, feta cheese, lettuce", DescriptionArm = "սև ու կանաչ ձիթապտուղ, չերրի լոլիկ, բուլղարական պղպեղ, մոցառելլա, պանիր ֆետա, հազար", DescriptionRus = "черные и зеленые оливки, помидоры черри, болгарский перец, моцарелла, сыр фета, листья салата" });
            pizzas.Add(new Product { Name = "Estate in Italiano 1 piece", NameArm = "Էստատե ին իտալյանո 1 կտոր", NameRus = "Эстате ин Италиано 1 кусок", Price = "590/3540", PicPath = "/Resources/Italy/estante in italiano 1 piece.jpg", Description = "black and green olives, cherry tomatoes, bell peppers, mozzarella, feta cheese, lettuce", DescriptionArm = "սև ու կանաչ ձիթապտուղ, չերրի լոլիկ, բուլղարական պղպեղ, մոցառելլա, պանիր ֆետա, հազար", DescriptionRus = "черные и зеленые оливки, помидоры черри, болгарский перец, моцарелла, сыр фета, листья салата" });


            categories.Add(new Categorie { Name = "Pizzas", NameArm = "Պիցցաներ", NameRus = "Пиццы", Products = pizzas, CategoriePic = "/Resources/Italy/Cover/Պիցցա.png" });


            List<Product> pastas = new List<Product>();

            pastas.Add(new Product { Name = "Arrabbiata /250 g/", NameArm = "Արաբիատա /250գր/", NameRus = "Арабиата /250 гр./", Price = "1300", PicPath = "/Resources/Italy/Պաստա Արաբիատա.jpg", Description = "chilli, basil, tomato sauce", DescriptionArm = "չիլի պղպեղ, բազիլիկ, տոմատային սոուս", DescriptionRus = "перец чили, базилик, томатный соус" });
            pastas.Add(new Product { Name = "Carbonara /300 g/", NameArm = "Կարբոնարա /300գր/", NameRus = "Карбонара /300 гр./", Price = "1600", PicPath = "/Resources/Italy/Պաստա Կարբոնարա.jpg", Description = "bacon, cream, white wine", DescriptionArm = "բեկոն, սերուցք, սպիտակ գինի", DescriptionRus = "бекон, сливки, белое вино" });
            pastas.Add(new Product { Name = "Bolognese /350 g/", NameArm = "Բոլոնեզ /350գր/", NameRus = "Болоньезе /350 гр./", Price = "1500", PicPath = "/Resources/Italy/Պաստա Բոլոնեզ.jpg", Description = "veal fillet, red wine, tomato sauce", DescriptionArm = "հորթի փափկամիս , կարմիր գինի,  տոմատային սոուս", DescriptionRus = "филе телятины, красное вино, томатный соус" });
            pastas.Add(new Product { Name = "Pasta with salmon in creamy sauce /320g/", NameArm = "Պաստա սաղմոնով սերուցքային սոուսով  /320գր/ ", NameRus = "Паста с лососем в сливочном соусе /320гр./", Price = "2500", PicPath = "/Resources/Italy/Պաստա Սաղմոնով.jpg", Description = "cream 20%, Pesto sauce, salmon fillet", DescriptionArm = "սերուցք 20%, պեստո սոուս, սաղմոնի ֆիլե", DescriptionRus = "сливки 20%, соус Песто, филе лосося" });
            pastas.Add(new Product { Name = "Pasta with veal in tomato-cream sauce /320 g/", NameArm = "Պաստա հորթի մսով տոմատա-սերուցքային սոուսով / 320գր / ", NameRus = "Паста с телятиной в томатно - сливочном соусе / 320 гр./ ", Price = "1600", PicPath = "/Resources/Italy/Հորթի միս տոմատային սերուցքով.jpg", Description = "veal fillet, mushrooms, cream, tomato sauce", DescriptionArm = "սունկ շամպինյոն, սերուցք, տոմատային սոուս,հորթի փափկամիս", DescriptionRus = "филе телятины, шампиньоны, сливки, томатный соус " });
            pastas.Add(new Product { Name = "Alfredo /300 g/", NameArm = "Ալֆրեդո /300գր/", NameRus = "Альфредо /300 гр./", Price = "1600", PicPath = "/Resources/Italy/Պաստա Ալֆրեդո.jpg", Description = "chicken breast, mushrooms, cream", DescriptionArm = "հավի կրծքամիս,  սունկ  շամպինյոն,  սերուցք", DescriptionRus = "куриная грудка, шампиньоны, сливки" });
            pastas.Add(new Product { Name = "Pasta Frutti di Mare", NameArm = "Պաստա Դի Մարե, 320 գ", NameRus = "Паста Фрутти ди Маре", Price = "3200", PicPath = "/Resources/Italy/Պաստա դի մարե.jpg", Description = "shrimps, spinach, basilic, cheese, cherry tomatoes, cream", DescriptionArm = "ծովախեցգետին, սպանախ, բազիլիկ, պանիր, չերրի լոլիկ, օրեգանո", DescriptionRus = "креветки, шпинат, базилик, сыр, помидоры черри, орегано" });
            pastas.Add(new Product { Name = "Pasta gorgonzola", NameArm = "Պաստա գորգոնզոլա, 300 գ", NameRus = "Паста с соусом из горгонзолы", Price = "1600", PicPath = "/Resources/Italy/Պաստա գորգոնզոլա.jpg", Description = "cream cheese, cherry tomatoes, onions, roquefort cheese, cream", DescriptionArm = "կրեմ չիզ, չերրի լոլիկ, սոխ, ռոկֆոր պանիր, սերուցք", DescriptionRus = "крем чиз, помидоры черри, лук, сыр рокфор, сливки" });
            pastas.Add(new Product { Name = "Pasta Verde with pesto sauce /320 g/", NameArm = "Պաստա Վեռդե պեստո սոուսով, 320 գ", NameRus = "Паста Верде с соусом песто /320 гр./", Price = "1400", PicPath = "/Resources/Italy/Պաստա Վեռդե պեստո սոուսով.jpg", Description = "bell pepper, pumpkin, carrot, broccoli, basil, pesto sauce, cherry tomatoes", DescriptionArm = "բուլղարական պղպեղ, դդմիկ, գազար, բրոկոլի, բազիլիկ, պեստո սոուս, չերրի լոլիկ", DescriptionRus = "болгарский перец, тыква, морковь, брокколи, базилик, соус песто, помидоры черри" });


            categories.Add(new Categorie { Name = "Pastas", NameArm = "Պաստաներ", NameRus = "Паста", Products = pastas, CategoriePic = "/Resources/Italy/Cover/Պաստա.png" });


            List<Product> hotDishes = new List<Product>();

            hotDishes.Add(new Product { Name = "Lasagne Bolognese /400 g/", NameArm = "Լազանյա բոլոնեզի միջուկով /400գր/", NameRus = "Лазанья Болоньезе /400 гр./ ", Price = "2600", PicPath = "/Resources/Italy/Լազանյա բոլոնեզի միջուկով.jpg", Description = "veal fillet, pasta (lasagna), tomato sauce, béchamel", DescriptionArm = "տոմատային սոուս, բեշամել, մակարոն (լազանի), հորթի փափկամիս", DescriptionRus = "филе телятины, паста (лазанья), томатный соус, бешамель " });
            hotDishes.Add(new Product { Name = "Four Cheese Lasagne /400 g/", NameArm = "Լազանյա 4 պանիր /400գր/", NameRus = "Лазанья Четыре сыра/400 гр./", Price = "2400", PicPath = "/Resources/Italy/Լազանյա 4 պանիր.jpg", Description = "pasta (lasagna), cheddar, parmesan, dorblu, mozzarella", DescriptionArm = "մակարոն (լազանի), չեդդեր,   պարմեզան, դորբլյու, մոցառելլա", DescriptionRus = "паста (лазанья), чеддер, пармезан, дорблю, моцарелла" });
            hotDishes.Add(new Product { Name = "Chicken Alfredo Roll /320 g/", NameArm = "Ռոլլ Ալֆրեդո /320գր/", NameRus = "Ролл Альфредо /320 гр./", Price = "1800", PicPath = "/Resources/Italy/ՌոլլԱլֆրեդո.jpg", Description = "chicken breast, cherry tomatoes, mushrooms, pesto sauce", DescriptionArm = "հավի կրծքամիս, չերրի լոլիկ, սոունկ, պեստո", DescriptionRus = "куриная грудка, помидоры черри, грибы, соус песто" });
            hotDishes.Add(new Product { Name = "Beef Alfredo Roll /320 g/", NameArm = "Ռոլլ Ալֆրեդո տավարի մսով/320գր/", NameRus = "Ролл Альфредо с говядиной /320 гр./", Price = "2100", PicPath = "/Resources/Italy/Beef roll alfredo.jpg", Description = "beef, cherry tomatoes, mushrooms, pesto sauce", DescriptionArm = "տավարի միս, չերրի լոլիկ, սոունկ, պեստո", DescriptionRus = "филе говядины, помидоры черри, грибы, соус песто" });
            hotDishes.Add(new Product { Name = "Subs with veal", NameArm = "Սաբս հորթի մսով", NameRus = "Сабы с телятиной", Price = "1200", PicPath = "/Resources/Italy/Սաբս հորթի մսով.jpg", Description = "veal, dough, cherry tomatoes, purple cabbage, balsamic vinegar", DescriptionArm = "hորթի միս, խմոր, չերրի լոլիկ, մանուշակագույն կաղամբ, բալզամիկ քացախ", DescriptionRus = "телятина, тесто, помидоры черри, капуста краснокочанная, уксус бальзамический" });
            hotDishes.Add(new Product { Name = "Beef stroganoff impasto, beef", NameArm = "Բիֆստրոգանով իմպաստո, տավարի մսով", NameRus = "Бефстроганов Импасто с говядиной", Price = "3200", PicPath = "/Resources/Italy/Բիֆստրոգանով իմպաստո, տավարի մսով.jpg", Description = "beef, champignon, mozarella cheese, parmesan cheese, cream, oregano", DescriptionArm = "տավարի փափկամիս, շամպինիոն, մոցառելլա, պառմեզան, սերուցք, օրեգանո", DescriptionRus = "филе говядины, шампиньоны, сыр моцарелла, пармезан, сливки, орегано" });
            hotDishes.Add(new Product { Name = "Beef stroganoff impasto, chicken", NameArm = "Բիֆստրոգանով իմպաստո,  հավի մսով", NameRus = "Бефстроганов Импасто с курицей", Price = "2500", PicPath = "/Resources/Italy/Բիֆստրոգանով իմպաստո,  հավի մսով.jpg", Description = "chicken, champignon, mozarella cheese, parmesan cheese, cream, oregano", DescriptionArm = "հավի կրծքամիս, շամպինիոն, մոցառելլա, պառմեզան, սերուցք, օրեգանո", DescriptionRus = "куриная грудка, шампиньоны, моцарелла, пармезан, сливки, орегано" });




            categories.Add(new Categorie { Name = "Hot dishes", NameArm = "Տաք ուտեստներ", NameRus = "Горячие блюда", Products = hotDishes, CategoriePic = "/Resources/Italy/Cover/hot dishes.png" });



            List<Product> soups = new List<Product>();

            soups.Add(new Product { Name = "Mushroom cream soup /250 g/", NameArm = "Սնկով կրեմապուր /250գր/", NameRus = "Грибной крем-суп /250 гр./", Price = "650", PicPath = "/Resources/Italy/Սնկով կրեմապուր.jpg", Description = "champignons, potatoes, cream", DescriptionArm = "սունկ  շամպինյոն, կարտոֆիլ, սերուցք", DescriptionRus = "шампиньоны, картофель, сливки" });
            soups.Add(new Product { Name = "Pumpkin cream soup /250 g/", NameArm = "Դդումով կրեմապուր/250գր/", NameRus = "Тыквенный крем-суп /250 гр./", Price = "650", PicPath = "/Resources/Italy/Դդմով կրեմապուր.jpg", Description = "pumpkin, carrots, potatoes, cream", DescriptionArm = "դդում, գազար, կարտոֆիլ, սերուցք", DescriptionRus = "тыква, морковь, картофель, сливки" });
            soups.Add(new Product { Name = "Broccoli cream-soup", NameArm = "Բրոկոլիով կրեմապուր", NameRus = "Крем-суп из брокколи", Price = "800", PicPath = "/Resources/Italy/Բրոկոլիով կրեմ ապուր.jpg", Description = "broccoli, spinach, cream-cheese, carrot, cream, quail egg, basilic", DescriptionArm = "բրոկոլի, սպանախ, կրեմ չիզ, գազար, սերուցք, լորի ձու, բազիլիկ", DescriptionRus = "брокколи, шпинат, крем чиз, морковь, сливки, перепелиное яйцо, базилик" });
            soups.Add(new Product { Name = "Gazpacho", NameArm = "Գասպաչո", NameRus = "Гаспачо", Price = "800", PicPath = "/Resources/Italy/Գասպաչոjpg.jpg", Description = "bell peppers, tomato, celery, basilic, garlic, toast bread", DescriptionArm = "բուլղարական պղպեղ, լոլիկ, մաղադանոս, բազիլիկ, սխտոր, տոստի հաց", DescriptionRus = "перец болгарский, помидоры, петрушка, базилик, чеснок, тост" });
            soups.Add(new Product { Name = "Minestrone", NameArm = "Մինեստրոնե", NameRus = "Минестроне", Price = "650", PicPath = "/Resources/Italy/minestrone.jpg", Description = "green beans, broccoli, cheese Gran Spicco, celery, bell pepper", DescriptionArm = "կանաչ լոբի, բրոկոլի, պանիր գրան սպիկկո, նեխուր, բուլղարական պղպեղ", DescriptionRus = "зеленая фасоль, брокколи, сыр гран спико, сельдерей, болгарский перец" });


            categories.Add(new Categorie { Name = "Soups", NameArm = "Ապուրներ", NameRus = "Супы", Products = soups, CategoriePic = "/Resources/Italy/Cover/soups.png" });

            List<Product> salads = new List<Product>();

            salads.Add(new Product { Name = "Caesar with chicken /230g/", NameArm = "Կեսար հավի մսով /230գր/ ", NameRus = "Цезарь с курицей /230 гр./", Price = "1400", PicPath = "/Resources/Italy/Աղցան կեսար հավի մսով.jpg", Description = "chicken breast, Iceberg lettuce, Romano lettuce, Caesar sauce", DescriptionArm = "այսբերգ հազար, ռոմանո,  կեսարի սոուս, հավի  կրծքամիս", DescriptionRus = "куриная грудка, салат айсберг, салат романо, соус цезарь " });
            salads.Add(new Product { Name = "Caesar with seafood /240g/", NameArm = "Կեսար ծովամթերքով/240գր/  ", NameRus = "Цезарь с морепродуктами /240 гр./", Price = "1700", PicPath = "/Resources/Italy/Աղցան Կեսար ծովամթերքով.jpg", Description = "seafood, Iceberg lettuce, Romano lettuce, Caesar sauce", DescriptionArm = "այսբերգ հազար, ռոմանո,  կեսարի սոուս, ծովամթերք", DescriptionRus = "морепродукты, салат айсберг, салат романо, соус цезарь " });
            salads.Add(new Product { Name = "Caprese with Pesto sauce /200g/", NameArm = "Կապրեզե պեստո սոուսով /200գր/", NameRus = "Капрезе с соусом Песто /200 гр./", Price = "1200", PicPath = "/Resources/Italy/Աղցան կապրեզե.jpg", Description = "milk mozzarella, tomatoes, pesto sauce", DescriptionArm = "կաթնային մոցառելլա, լոլիկ, պեստո սոուս", DescriptionRus = "молочная моцарелла, помидоры, соус песто" });
            salads.Add(new Product { Name = "Arugula with cherry tomatoes /200 g/", NameArm = "Ռուկկոլա չերրիով/200գր/", NameRus = "Руккола с помидорами черри /200 гр./", Price = "1500", PicPath = "/Resources/Italy/Աղցան Ռուկոլա չերիով.jpg", Description = "arugula, lettuce, cherry tomatoes, carpaccio sauce", DescriptionArm = "ռուկկոլա, հազար, կարպաչո սոուս, չերրի լոլիկ", DescriptionRus = "руккола, листья салата, помидоры черри, соус карпаччо" });
            salads.Add(new Product { Name = "Fiori /240 g/", NameArm = "Ֆիորի /240գր/", NameRus = "Фьори /240 гр./", Price = "1250", PicPath = "/Resources/Italy/Salad Fiori.jpg", Description = "lavash, bell pepper, dry mozzarella, bacon", DescriptionArm = "լավաշ, բուլղարական պղպեղ, չոր  մոցառելլա, բեկոն", DescriptionRus = "лаваш, болгарский перец, сухая моцарелла, бекон" });
            salads.Add(new Product { Name = "Naples /240 g/", NameArm = "Նապոլի/240գր/", NameRus = "Неаполь /240 гр./", Price = "750", PicPath = "/Resources/Italy/Աղցան Նապոլի.jpg", Description = "chicken breast, red beans, bell pepper", DescriptionArm = "կարմիր լոբի, հավի կրծքամիս,  բուլղարական պղպեղ", DescriptionRus = "куриная грудка, красная фасоль, болгарский перец" });
            salads.Add(new Product { Name = "Di Polo Arosto", NameArm = "Դի Պոլո Առոստո", NameRus = "Аросто ди Поло", Price = "1800", PicPath = "/Resources/Italy/Դի պոլո արոստո.jpg", Description = "chicken breast, spinach, puff pastry, couscous, quail egg", DescriptionArm = "հավի կրծքամիս, սպանախ, շերտավոր խմոր, կուս կուս, լորի ձու", DescriptionRus = "куриная грудка, шпинат, слоеное тесто, кускус, перепелиные яйца" });
            salads.Add(new Product { Name = "Vitello", NameArm = "Վիտելլո", NameRus = "Вителло", Price = "2400", PicPath = "/Resources/Italy/Վիտելլո.jpg", Description = "beef, puff pastry, ginger, arugula, spinach", DescriptionArm = "տավարի փափկամիս, շերտավոր խմոր, իմբիր, ռուկոլա, սպանախ", DescriptionRus = "филе говядины, слоеное тесто, имбирь, руккола, шпинат" });
            salads.Add(new Product { Name = "Summer Caprese Farro", NameArm = "Ամառային կապրեզե Ֆառռո", NameRus = "Летний Капрезе Фарро", Price = "1900", PicPath = "/Resources/Italy/Summer Caprese Farro.jpg", Description = "Feta cheese, cherry tomatoes, lettuce, green olives, cucumber, basil", DescriptionArm = "Պանիր ֆետա, չերրի լոլիկ, հազար, սև և կանաչ ձիթապտուղ, վարունգ, բազիլիկ", DescriptionRus = "Сыр фета, помидоры черри, листья салата, оливки, огурец, базилик" });
            salads.Add(new Product { Name = "Italian Couscous", NameArm = "Իտալական կուսկուս", NameRus = "Кускус по-итальянски", Price = "1200", PicPath = "/Resources/Italy/Italian kuskus.jpg", Description = "Arugula, bell pepper, cherry tomatoes, pumpkin, gran spicco cheese, green peas", DescriptionArm = "Ռուկոլա, բուլղարական պղպեղ, չերրի լոլիկ, դդմիկ, պանիր գրան սպիչո, կանաչ ոլոռ", DescriptionRus = "Руккола, болгарский перец, помидоры черри, тыква, сыр гран спико, зеленый горошек" });


            categories.Add(new Categorie { Name = "Salads", NameArm = "Աղցաններ", NameRus = "Салаты", Products = salads, CategoriePic = "/Resources/Italy/Cover/salads.png" });


        }
    }
}
